---
 - name: comment /etc/motd
   copy:
     content: "{{ ansible_fqdn }} Managed by Ansible\n"
     dest: /etc/motd
   tags: common
 - name: setup user passwordless on target
   lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sysadmin\s'
      line: '%sysadmin ALL=(ALL) NOPASSWD: ALL'
   tags: common
 - name: Enable AddressFamily inet on /etc/ssh/sshd_config , required to disable ipv6
   lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^%AddressFamily\s'
      line: 'AddressFamily inet'
   notify:
      - restart sshd
   tags: common
 - name: Add ipv6 disable on /etc/sysctl.conf, Set ipv6 kernel parameters disabled
   sysctl: name={{ item.pname }} value={{ item.value }} state=present sysctl_file=/etc/sysctl.conf sysctl_set=yes reload=yes
   with_items:
     - { pname: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
     - { pname: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
   tags: common
 - name: Update /etc/hosts file
   lineinfile:
     dest: /etc/hosts
     state: present
     regexp: '{{ ansible_default_ipv4.address }}\s'
     line: '{{ ansible_default_ipv4.address }}    {{ ansible_fqdn }}'
   ignore_errors: yes
   tags: common
 - name: Update /etc/sysconfig/network-script/ifcfg
   template:
     src: "{{ if_template }}"
     dest: /etc/sysconfig/network-scripts/ifcfg-ens192
     backup: yes
   tags: common
 - name: Update /etc/sysconfig/network file on target
   template:
     src: "{{ net_template }}"
     dest: /etc/sysconfig/network
     backup: yes
   ignore_errors: yes
 - name: Update /etc/resolv.conf file on target
   template:
     src: "{{ dns_template }}"
     dest: /etc/resolv.conf
     backup: yes
   tags: common
 - name: restart network
   shell: 'sudo systemctl restart network'
   async: 2
   poll: 2

   tags: common
 - name: Install required pkgs
   yum:
     name:
       - "{{ delta_pkg }}"
       - "{{ perl_pkg }}"
       - "{{ bindu_pkg }}"
       - "{{ net_pkg }}"
       - "{{ git_pkg }}"
     state: latest
   tags: common
 - name: Uninstall dhcp packages
   yum: name={{ item }} state=absent
   with_items:
     - dhclient.x86_64
     - dhcp-common.x86_64
     - dhcp-libs.x86_64
   tags: common
 - name: Disable NetworkManager service
   service: name=NetworkManager state=stopped enabled=no
   tags: common
 - name: copy current image kernel
   shell:
     'sudo cp /boot/initramfs-`uname -r`.img /boot/initramfs-`uname -r`.img.backup'
   tags: common
 - name: update the system
   yum: name=* state=latest
   tags: common 
 - name : compile new kernel after removed Nmcli and dhcp client
   shell:
     'sudo dracut -fv'
   register: task_result
   tags: common
 - name: Reboot immediately if there was a change in the kernel image.
   shell: 'sleep 5 && sudo /sbin/shutdown -r now'
   async: 1
   poll: 0
   when: task_result is changed
   tags: common
 - name: Wait for the reboot to complete if there was a change.
   wait_for_connection:
     connect_timeout: 20
     sleep: 5
     delay: 7
     timeout: 300
   when: task_result is changed
   tags: common
 - ping: 
   tags: common
