---
 - name: update the system
   become: true
   yum: name=* state=latest
   when: ansible_os_family == "Redhat"
   #tags: full-deploy
 - name: setup user passwordless on target
   become: true
   lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sysadmin\s'
      line: '%sysadmin ALL=(ALL) NOPASSWD: ALL'
   #tags: full-deploy
 - name: Enable AddressFamily inet on /etc/ssh/sshd_config , required to disable ipv6
   become: true
   lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^%AddressFamily\s'
      line: 'AddressFamily inet'
   notify:
      - restart sshd
 - name: Add ipv6 disable on /etc/sysctl.conf, Set ipv6 kernel parameters disabled
   become: true
   sysctl: name={{ item.pname }} value={{ item.value }} state=present sysctl_file=/etc/sysctl.conf sysctl_set=yes reload=yes
   with_items:
     - { pname: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
     - { pname: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
 - name: Update /etc/hosts file
   become: true
   lineinfile:
     dest: /etc/hosts
     state: present
     regexp: '{{ ansible_default_ipv4.address }}\s'
     line: '{{ ansible_default_ipv4.address }}    {{ ansible_fqdn }}'
 - name: Install required pkgs
   become: true
   yum:
     name:
       - "{{ perl_pkg }}"
       - "{{ bindu_pkg }}"
       - "{{ net_pkg }}"
     state: latest
 - name: Uninstall dhcp packages
   become: true
   yum: name={{ item }} state=absent
   with_items:
     - dhclient.x86_64
     - dhcp-common.x86_64
     - dhcp-libs.x86_64
 - name: Disable NetworkManager service
   become: true
   service: name=NetworkManager state=stopped enabled=no
 - name: Update /etc/sysconfig/network file on target
   become: true
   template:
     src: "{{ net_template }}"
     dest: /etc/sysconfig/network
     backup: yes
 - name: Update /etc/resolv.conf file on target
   become: true
   template:
     src: "{{ dns_template }}"
     dest: /etc/resolv.conf
     backup: yes
 - name: copy current image kernel
   shell:
     'sudo cp /boot/initramfs-`uname -r`.img /boot/initramfs-`uname -r`.img.backup'
 - name : compile new kernel after removed Nmcli and dhcp client
   shell:
     'sudo dracut -fv'
   register: task_result
 - name: Reboot immediately if there was a change in the kernel image.
   shell: 'sleep 5 && sudo /sbin/shutdown -r now'
   async: 1
   poll: 0
   when: task_result is changed
 - name: Wait for the reboot to complete if there was a change.
   wait_for_connection:
     connect_timeout: 20
     sleep: 5
     delay: 7
     timeout: 300
   when: task_result is changed
 - ping: 

