---
- hosts: localhost
  connection: local
  
#  roles:
#   - role: vmware
#   - role: common
  tasks:
    - include_role: 
        name: vmware
      tags: 
        - full-deploy
        - full-delete
    - include_role: 
        name: common
      tags:
        - full-deploy
