---
#- hosts: vms, openstack
- hosts: localhost
  connection: local
  become: true 
  gather_facts: false
  #roles:
  tasks:
    - include_role:
        name: vmware 
      tags:
        - manual-deploy 
        - full-deploy
        - full-delete
    - include_role: 
        name: common
      tags:
        - common
