---
- hosts: localhost
  connection: local
  
  roles:
  tasks:
    - include_role:
        name: vmware 
      tags: 
        - full-deploy
        - full-delete
    - include_role: 
        name: common
      tags:
        - common
