---
- hosts: vms, openstack

- name: setup user passwordless on target
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sysadmin\s'
      line: '%sysadmin ALL=(ALL) NOPASSWD: ALL'

